export const SET_USER_NAME = '[SET USER NAME]';
export const SET_USER_LIST = '[SET USER LIST]';
export const GO_TO_GAMESCREEN = '[GO_TO_GAMESCREEN]';
export const CLIENT_GAME_STAGED = '[CLIENT GAME STAGED]';
export const START_GAME = '[START_GAME]';
export const SHARE_GAME_STATE = '[SHARE GAME STATE]';
export const RECEIVE_GAME_STATE = '[RECEIVE GAME STATE]';
